"""empty message

Revision ID: b0fff62a1faf
Revises: 
Create Date: 2019-04-18 14:56:32.251927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fff62a1faf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	with op.batch_alter_table('account') as batch_op:
		batch_op.drop_column('name')
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('account', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('name', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###

