"""empty message

Revision ID: d000ff0469f4
Revises: 3100e57438dc
Create Date: 2019-04-19 18:24:37.143989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd000ff0469f4'
down_revision = '3100e57438dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['password'])
    op.create_unique_constraint(None, 'account', ['username'])
    op.add_column('messages', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'date')
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
